Merge for yang
TLdgh/Data_Analysis_Proj_1 pull request #18
Opened 2023-10-03 18:04 UTC by UOYangLyu

Added gap plot part, plz review

2023-10-03 21:04 UTC, TLdgh commented
I added the combined map chart for the final and predicted result. Please review and merge to main!

2023-10-03 22:53 UTC, 9242720 approved these changes

2023-10-04 02:05 UTC, TLdgh requested changes
Please review again.

2023-10-04 02:30 UTC, TLdgh approved these changes
map chart updated.

2023-10-04 02:30 UTC, merged