1、Analysis of the connection between pollster and grade
TLdgh/Data_Analysis_Proj_1 pull request #8
Opened 2023-09-22 02:32 UTC by 9242720

1、Analysis of the connection between pollster and grade
2、Draw the pie chart of the variable "grade"

2023-09-22 03:25 UTC, TLdgh requested changes
I'm suggesting something here:
1. Let's put that .DS_Store in the gitignore, and keep it only in your local laptop.
2. I like that the rmd file is created for this specific grade chart task! We should all take this approach by creating a separate rmd file other than the main project rmd file, and we will copy paste things in there once we decide to push.
3. Try to put relevant codes in the same chunk, for example you can combine line 14-15 with 9-10 by putting na.omit there. This way you have much cleaner code chunk. And you can simply add a comment to say that you're omitting NA's.
4. I like the pie chart! Let's add it in the main file. Could you make more details for this chart? For example, put a legend to show that those ABC's are Grades, and the title should be Proportion of Grades or something.

2023-09-26 02:35 UTC, TLdgh requested changes
Chart approved! You can add your content into the main file!

2023-09-26 14:42 UTC, Aych12 approved these changes

2023-09-27 00:38 UTC, UOYangLyu approved these changes

2023-09-27 17:22 UTC, TLdgh approved these changes
Approved. Merged into main.

2023-09-27 17:23 UTC, merged